"""add facebook_url to business

Revision ID: 031613d39afa
Revises: 0a027c359ec4
Create Date: 2026-04-16 23:05:43.042680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031613d39afa'
down_revision = '0a027c359ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
