"""increase product description length

Revision ID: 561c35f6fa8d
Revises: 6911351097da
Create Date: 2026-05-11 14:57:49.101600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561c35f6fa8d'
down_revision = '6911351097da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
